"""empty message

Revision ID: 0986d964663b
Revises: b93bf5b71844
Create Date: 2021-02-17 00:00:10.140920

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0986d964663b'
down_revision = 'b93bf5b71844'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipes', sa.Column('timestamp', sa.DateTime(), nullable=True))
    op.add_column('recipes', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_recipes_timestamp'), 'recipes', ['timestamp'], unique=False)
    op.create_foreign_key(None, 'recipes', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'recipes', type_='foreignkey')
    op.drop_index(op.f('ix_recipes_timestamp'), table_name='recipes')
    op.drop_column('recipes', 'user_id')
    op.drop_column('recipes', 'timestamp')
    # ### end Alembic commands ###
